/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import Fabrica.Factoria;
import Fabrica.Partes;
import controlador.puente;
import javax.swing.ImageIcon;
/**
 *
 * @author David
 */
public class viñeta extends javax.swing.JFrame  {
    Partes f = Factoria.getParte("viñeta");

    /**
     * Creates new form Scrollbar
     */
    public viñeta() {
        initComponents();
        ImageIcon ico = new ImageIcon(getClass().getResource("/imgcomp/comp1p.png"));
        puente.controladorico(PB1,ico);
        
        ico = new ImageIcon(getClass().getResource("/imgcomp/comp2p.png"));
        puente.controladorico(PB2,ico);
        
        ico = new ImageIcon(getClass().getResource("/imgcomp/comp3p.png"));
        puente.controladorico(PB3,ico);
        
        ico = new ImageIcon(getClass().getResource("/imgcomp/comp4p.png"));
        puente.controladorico(PB4,ico);
        
        ico = new ImageIcon(getClass().getResource("/imgcomp/comp5p.png"));
        puente.controladorico(PB5,ico);
        
        ico = new ImageIcon(getClass().getResource("/imgcomp/comp6p.png"));
        puente.controladorico(PB6,ico);
        
        ico = new ImageIcon(getClass().getResource("/imgcomp/comp7p.png"));
        puente.controladorico(PB7,ico);
        
         puente.controladorfon(jPanel2,"/img/fv.jpg");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PB1 = new javax.swing.JButton();
        PB2 = new javax.swing.JButton();
        PB3 = new javax.swing.JButton();
        PB4 = new javax.swing.JButton();
        PB5 = new javax.swing.JButton();
        PB6 = new javax.swing.JButton();
        PB7 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Viñetas");

        PB1.setRolloverEnabled(false);
        PB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB1ActionPerformed(evt);
            }
        });

        PB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB2ActionPerformed(evt);
            }
        });

        PB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB3ActionPerformed(evt);
            }
        });

        PB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB4ActionPerformed(evt);
            }
        });

        PB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB5ActionPerformed(evt);
            }
        });

        PB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB6ActionPerformed(evt);
            }
        });

        PB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PB7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PB4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PB1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PB5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PB7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PB3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PB6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(412, 412, 412))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PB3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PB2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PB1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PB4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PB5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PB6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(PB7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1209, 1209, 1209))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB2ActionPerformed
        puente.controladorimg(f, "2");
    }//GEN-LAST:event_PB2ActionPerformed

    private void PB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB1ActionPerformed
        puente.controladorimg(f, "1");
    }//GEN-LAST:event_PB1ActionPerformed

    private void PB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB3ActionPerformed
       puente.controladorimg(f, "3");
    }//GEN-LAST:event_PB3ActionPerformed

    private void PB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB4ActionPerformed
        puente.controladorimg(f, "4");
    }//GEN-LAST:event_PB4ActionPerformed

    private void PB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB5ActionPerformed
       puente.controladorimg(f, "5");
    }//GEN-LAST:event_PB5ActionPerformed

    private void PB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB6ActionPerformed
        puente.controladorimg(f, "6");
    }//GEN-LAST:event_PB6ActionPerformed

    private void PB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PB7ActionPerformed
        puente.controladorimg(f, "7");
    }//GEN-LAST:event_PB7ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PB1;
    private javax.swing.JButton PB2;
    private javax.swing.JButton PB3;
    private javax.swing.JButton PB4;
    private javax.swing.JButton PB5;
    private javax.swing.JButton PB6;
    private javax.swing.JButton PB7;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
